eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
server:
  port: 9999
    
spring:
  application:
    name: green-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/heiliang27/green/
          searchPaths: config
#          username: 
#          password: