eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/      

server:
  port: 8888

zuul:
  routes:
    api-a:
      path: /admin/**
      serviceId: green-admin
    api-b:
      path: /user/**
      serviceId: green-user