eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/      

server:
  port: 8888

zuul:
  routes:
    admin:
      path: /admin/**
      serviceId: green-admin
    api-b:
      path: /user/**
      serviceId: green-user
admin:
  ribbon:
    listOfServers: localhost:8080,localhost:8081 #example.com,google.com