# 服务注册中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  
    healthcheck:  # 健康检查
      enabled: true
  instance:
    appname: green-zuul   
#服务端口
server:
  port: 8888
# 路由zuul配置分发拦截
zuul:
  routes:
    admin:
      path: /admin/**
      serviceId: green-admin
    api-b:
      path: /user/**
      serviceId: green-user
# 不使用eureka时 手动集群 admin:
#  ribbon:
#    listOfServers: localhost:8080,localhost:8081 #example.com,google.com
    
hello: hi my name is xiaoming - green-zuul-dev