# eureka服务配置中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ 
    healthcheck:  # 健康检查
      enabled: true
  instance:
    appname: green-admin 
# 服务端口     
server:
  port: 8081
# 业务内容
hello: hi my name is xiaoming - green-admin-dev