# eureka服务配置中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ 
    healthcheck:  # 健康检查
      enabled: true
  instance:   
    prefer-ip-address: true
    #可能比较长，复制的时候请写在一行
    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port}}
    appname: green-admin
# 服务端口     
server:
  port: 8080
# 业务内容
hello: hi my name is xiaoming - green-admin-dev