# eureka服务配置中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ 
    healthcheck:  # 健康检查
      enabled: true
  instance:      
    prefer-ip-address: true
    #可能比较长，复制的时候请写在一行 
    #instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}
    #${spring.application.name}:${server.port}
    appname: green-admin
# 服务端口     
server:
  port: 8080

druid:
   datasource:
     driver-class-name: com.mysql.jdbc.Driver
     url: jdbc:mysql://qdm170159589.my3w.com/qdm170159589_db?useUnicode=true&characterEncoding=UTF8
     username: qdm170159589
     password: 12345678
mybatis:
    mapper-locations: "classpath*:mapper/*.xml"
   
